spring:
  application:
    name: miscale2pg

  docker:
    compose:
      stop:
        command: down

  mvc:
    problemdetails:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
