---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Java Tests
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@0def53c0fd8534bc13416c9469f5be45265824fd # v1.6.3
        with:
          java-version: "25"
          distribution: graalvm-community
          cache: gradle

      - name: Run Tests
        run: ./gradlew test --no-daemon

      - name: Run Native Tests
        run: ./gradlew nativeTest --no-daemon
